import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import "./globals.css";
import ThemeToggle from "../app/components/ThemeToggle";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} py-3 dark:bg-dark dark:text-white`}>
        <div style={{ display: "flex", gap: "1rem" }} className=" dark:bg-dark dark:text-white">
          <Link href="/">Home</Link>
          <Link href="/Portfolio">Portfolio</Link>
          <ThemeToggle />
        </div>
        {children}
      </body>
    </html>
  );
}
