import type { Metadata } from "next";
import Link from "next/link";
import { Inter } from "next/font/google";
import Navbar from "./components/Navbar";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div
          style={{
            height: "100px",
            background: "red",
            display: "flex",
            flexDirection: "column",
          }}
        >
          <div style={{ display: "flex", gap: "1rem" }}>
            <Link href="/Portfolio">Portfolio</Link>
            <Link href="/Home">Home</Link>
            <Link href="/Home/Coins">Coins</Link>

            <Link href="/Home/Coins/Compare">Compare</Link>
            <Link href="/Home/Convertor">Convertor</Link>
          </div>
          <Navbar />
        </div>

        {children}
      </body>
    </html>
  );
}
